### ISSUE TITLE
Zenodo::Resources::Object::Attributes lookup is broken

### ISSUE THREAD

**Issue by zdennis** [sprotocols/zenodo#4]
Zenodo::Resources::Object::Attributes lookup is broken, e.g.:

```
irb> attributes =     {
      'metadata' => {
        'title' => 'My first upload',
        'upload_type' => 'poster',
        'description' => 'This is my first upload',
        'creators' =>[{'name' => 'Doe, Jane','affiliation' => 'ZENODO'}]
      }
    }
irb> deposition = Zenodo.client.create_deposition(deposition:attributes)
(Object doesn't support #inspect)
=>
irb> deposition.inspect
NoMethodError: undefined method `files' for #<Zenodo::Resources::Deposition:0x007fb6f59ce9c0>
    from /Users/zdennis/.rvm/gems/ruby-2.2.1/gems/zenodo-0.0.6/lib/zenodo/resources/object/attributes.rb:55:in `method_missing'
    from /Users/zdennis/.rvm/gems/ruby-2.2.1/gems/zenodo-0.0.6/lib/zenodo/resources/object/attributes.rb:44:in `public_send'
    from /Users/zdennis/.rvm/gems/ruby-2.2.1/gems/zenodo-0.0.6/lib/zenodo/resources/object/attributes.rb:44:in `block (2 levels) in attributes'
    from /Users/zdennis/.rvm/gems/ruby-2.2.1/gems/zenodo-0.0.6/lib/zenodo/resources/object/attributes.rb:42:in `each'
    from /Users/zdennis/.rvm/gems/ruby-2.2.1/gems/zenodo-0.0.6/lib/zenodo/resources/object/attributes.rb:42:in `block in attributes'
    from /Users/zdennis/.rvm/gems/ruby-2.2.1/gems/zenodo-0.0.6/lib/zenodo/resources/object/attributes.rb:41:in `tap'
    from /Users/zdennis/.rvm/gems/ruby-2.2.1/gems/zenodo-0.0.6/lib/zenodo/resources/object/attributes.rb:41:in `attributes'
    from /Users/zdennis/.rvm/gems/ruby-2.2.1/gems/zenodo-0.0.6/lib/zenodo/resources/object.rb:25:in `inspect_attributes'
    from /Users/zdennis/.rvm/gems/ruby-2.2.1/gems/zenodo-0.0.6/lib/zenodo/resources/object.rb:19:in `inspect'
    from (irb):75
```

**Comment by dior001** [comment]
Thanks @zdennis nice work.
